### ISSUE TITLE
wrong css color for .tblcomment in theme.css and _common.scss

### ISSUE THREAD

**Issue by AJK-Muc** [adorade/boodark#34]
Original <code>.tblcomment {color: #009;}</code> is too dark in theme.css and _common.scss line 287
<br><img width="112" alt="original_bug" src="https://user-images.githubusercontent.com/46240166/216069424-d425c506-1f54-4ee3-83c7-98e9960affd5.png">
<br>Modified: <code>color: #CCC;</code> this is of course just a quick fix and should be something theme related of the taste of the original designer
<br><img width="112" alt="modified" src="https://user-images.githubusercontent.com/46240166/216069477-91500c0c-348b-4f26-bcd5-5d2b36ffdabf.png">

**Comment by adorade** [comment]
@AJK-Muc Thank you for reporting this issue. I will check as soon as possible

**Comment by adorade** [comment]
@AJK-Muc What version of phpMyAdmin are you using?
I'm trying to reproduce the issue in version 5.2.1 and can't.
Can you give me more information, maybe even a full screenshot.

BooDark only supports pma 5.2.0.
Thank you!

**Comment by adorade** [comment]
I already modified that file:
```scss
.tblcomment {
  font-size: 70%;
  font-weight: normal;
  color: $text-muted;   // color: #ced4da;
}
```
The problem is that I can't see the change when I do a visual test. I don't know exactly where to navigate to see the change. Maybe I'm missing something.

**Comment by adorade** [comment]
I understand now. brb 😉

**Comment by adorade** [comment]
Before:
![table-comments-before](https://user-images.githubusercontent.com/6474149/218530025-c4a9e606-ff80-457a-a61a-da4a00eeb7a3.png)

After:
![table-comments-after](https://user-images.githubusercontent.com/6474149/218530167-9d467c5a-6805-4752-a8d2-f63bb59b61ea.png)

Solved. Included in the next release.
Thank you for using BooDark! 🥇
