### ISSUE TITLE
Wrong code color on delete confirmation

### ISSUE THREAD

**Issue by adorade** [adorade/boodark#35]
Before:
![sql_query_bg_error_before](https://user-images.githubusercontent.com/6474149/219081277-04a87010-5c84-4255-b175-14788c789f4b.png)

After:
![sql_query_bg_error_after_dark](https://user-images.githubusercontent.com/6474149/219081520-e81d32c1-57d2-4c90-82f1-233b320d1b92.png)

**Comment by johntor** [comment]
I made a pull request in this!

**Comment by adorade** [comment]
@johntor thank you for your involvement. 👍 😉 I made the changes earlier but forgot to commit them.

Solved. Included in the next release.
Thank you for using BooDark! 🥇
