### ISSUE TITLE
wrong color for warnings when deleting records

### ISSUE THREAD

**Issue by AJK-Muc** [adorade/boodark#42]
PMA 5.2.1 with PHP 8.2.2 (Safari 16.3 on macOS 13.2)

Usually PMA shows me warnings as JS confirmation windows when I want to delete records, so you can't see it like that. But sometimes it shows this dialog:

Error:  same text color and background, which makes it unreadable (warning dialog when deleting records)
<img width="507" alt="Bildschirm­foto 2023-02-22 um 12 36 47" src="https://user-images.githubusercontent.com/46240166/220610844-8f3034ad-4749-4218-bd26-7541a28697b8.png">

Quick Fix: selecting the „imaginary text“ with the mouse makes it readable 😉
<img width="551" alt="Bildschirm­foto 2023-02-22 um 12 37 07" src="https://user-images.githubusercontent.com/46240166/220611457-d6dfedc3-6c65-41be-b3f4-d8eec9b4ce31.png">

**Comment by adorade** [comment]
@AJK-Muc solved already in https://github.com/adorade/boodark/pull/37
See also https://github.com/adorade/boodark/issues/35
In these days I will release a new version. 🚀  Stay close! 👍

**Comment by AJK-Muc** [comment]
wonderful, you're quite diligent 😊👍

**Comment by adorade** [comment]
@AJK-Muc try prerelease: https://github.com/adorade/boodark/releases/tag/v1.1.0-beta
