### ISSUE TITLE
Browse foreign values has a white BG

### ISSUE THREAD

**Issue by williamdes** [adorade/boodark#51]
### Describe the bug

![image](https://github.com/adorade/boodark/assets/7784660/78f2b351-236d-4e1d-ad79-ca5455ec92bc)

### To Reproduce

1. Use this dataset: https://github.com/phpmyadmin/phpmyadmin/issues/16013#issuecomment-1283849227
2. Double click to edit the relation like in the screenshot

### Expected behavior

Dark

### Additional context

- phpMyAdmin version: 5.2
- BooDark version: 1.1.0

**Comment by adorade** [comment]
![binary-uuid-dark](https://github.com/adorade/boodark/assets/6474149/fb7ce1d3-9bb9-4b06-bf9c-969670a177a4)

@williamdes I modified the code for `cEdit` in **common.scss**. If you can please check if it is what you expect. (see screenshot)

**Comment by williamdes** [comment]
> @williamdes I modified the code for cEdit in common.scss. If you can please check if it is what you expect. (see screenshot)

Thanks, it really looks good and nice !

**Comment by adorade** [comment]
![binary-uuid-input-focus-dark](https://github.com/adorade/boodark/assets/6474149/75dd85c3-3c90-4bc8-baf5-2da4b7d63128)

Updated input style. I will merge PR in the next days and the fix will be included in the next release.

**Comment by williamdes** [comment]
That's way better!
