### ISSUE TITLE
Editting fields cannot resize horizontally(only vertically) 

### ISSUE THREAD

**Issue by arionargo** [adorade/boodark#53]
When in edit screen of a routine(or other) the Definition field can only be resized vertically. 
It cannot be resized horizontally.
I have checked it with version 5.2.1 of phpMyAdmin using chromium(116) and firefox(117).

thanks

**Comment by adorade** [comment]
@arionargo thanks for the report. I will check as soon as possible.
Until then, could you post a screenshot?

**Comment by arionargo** [comment]
The behavior is as expected(resize both horizontally & vertically) with original theme and metro, 
but it is not as expected(resize only vertically) with the Bootstrap and boodark.

hope that helps

![Screenshot_20230911_144620](https://github.com/adorade/boodark/assets/4665973/047a798c-2331-402c-a63d-730b44ac8b30)

**Comment by adorade** [comment]
Well, BooDark is based on the Bootstrap theme.
Textarea style updated.
In these days I will release a new version. 🚀 Stay close! 👍
