### ISSUE TITLE
Font-Size

### ISSUE THREAD

**Issue by cmahlig** [adorade/boodark#57]
### Is your feature request related to a problem? Please describe.

I want to change the Font-Size, but i found no central point (variable)

### Describe the solution you'd like

A central point of variables to define the font sizes for the complete theme.

### Additional context

- BooDark version: 1.1.0

**Comment by maisondasilva** [comment]
@adorade I was going to open a request and saw this, is it possible to make the theme with a smaller font to be the same size as the original theme?

![Captura de tela 2023-11-08 183926](https://github.com/adorade/boodark/assets/11423362/c34e9d8e-751e-4056-8eb9-07d2a7209614)

**Comment by adorade** [comment]
@maisondasilva BooDark is based on Bootstrap theme, not pmahomme.
For pmahomme theme:
`--bs-body-font-size: 0.82rem;`
For Bootstrap and BooDark themes:
`--bs-body-font-size: 1rem;`
Check here: https://demo.phpmyadmin.net/QA_5_2/ (pma v5.2.2-dev, user root, pass empty)
So I won't change the theme in the future. You can try rebuilding the theme with the `--bs-body-font-size` value you want.
