### ISSUE TITLE
"Column Visibility" dropdown menu color issue

### ISSUE THREAD

**Issue by Lijahide** [adorade/boodark#6]
![boodark_menu](https://user-images.githubusercontent.com/49410375/198293909-50b1a48c-c26f-4442-84b1-ef618a38b746.PNG)

Colors make it nearly impossible to see the words in the menu.

**Comment by Lijahide** [comment]
possibly redundant specification: found in the table view.

not sure if this is fixed in your new version that hasn't been pulled yet.

**Comment by adorade** [comment]
@Lijahide thank you to report this issue. I'll check later.

**Comment by adorade** [comment]
New "Column Visibility" style with dark background

![column visibility](https://user-images.githubusercontent.com/6474149/198351426-96bd0add-1103-4c12-b2c6-96fddbb1b4d8.png)

**Comment by adorade** [comment]
The solution to the issue will be added in the next release.

**Comment by Lijahide** [comment]
Thanks a bunch looks great 👍
